### ISSUE TITLE
October CG meeting agenda (at TPAC)

### ISSUE THREAD

**Issue by binji** [WebAssembly/meetings#282]
Here are a list of the current proposals. Which of these shall we discuss at the upcoming in-person [CG meeting at TPAC](https://github.com/WebAssembly/meetings/blob/master/2018/TPAC.md)?

- [x] [Threads](https://github.com/WebAssembly/design/issues/1073) (champion @binji - [phase 1](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#1-feature-proposal-community-group))
    - Updates on memory model and spec (@conrad-watt and @rossberg)
    - [Race between memory.grow and access](https://github.com/WebAssembly/threads/issues/26#issuecomment-424742576)
- [x] [Garbage Collection](https://github.com/WebAssembly/design/issues/1079) (champion @rossberg - [phase 1](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#1-feature-proposal-community-group))
- [x] [Bulk memory operations](https://github.com/WebAssembly/design/issues/1114) (champion @binji - [phase 1](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#1-feature-proposal-community-group))
- [x] [ECMAScript module integration](https://github.com/WebAssembly/design/issues/1087) (champion @linclark - [phase 1](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#1-feature-proposal-community-group))
- [x] [Tail Call](https://github.com/WebAssembly/design/issues/1144) (champion @rossberg - [phase 1](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#1-feature-proposal-community-group))
- [x] [Multi-value](https://github.com/WebAssembly/design/issues/1146) (champion @rossberg - [phase 3](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#3-implementation-phase-community--working-group))
    - Move to stage 4? (blocked on implementation)
- [x] [Reference types](https://github.com/WebAssembly/design/issues/1203) (champion @rossberg - [phase 3](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#3-implementation-phase-community--working-group))
    - Move to stage 4? (blocked on implementation)
- [x] [Host bindings](https://github.com/WebAssembly/design/issues/1148) (champion @lukewagner - [phase 1](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#1-feature-proposal-community-group))
    - Recap problem statement: direct calls to any Web IDL methods/accessors from wasm
    - Recap developments since TPAC last year: extraction of the Reference Types proposal
    - Short browser update on any browser implementation progress toward Reference Types
    - Given Reference Types, what's left for Host Bindings to do?
      - The following are still missing when calling Web IDL:
        - Pass/receive a non-undefined receiver
        - Call as a constructor
        - Opt into unsigned interpretation of i32/i64 when converting to Number/BigInt
        - Callbacks: function reference types + func.bind (+ WeakRefs)
      - With Reference Types factored out into the core spec, consider renaming to "Web IDL Bindings"?
    - Observation: the real value prop to use any of this (from browser POV) is fast Web IDL calls
    - So, proposal: let's define a milestone that combines Reference Types + Web IDL Bindings MVP
    - Some WebGL/Emscripten glue code can move into WASM bytecode; this will help fast Web IDL calls
    - How would this look in the source language?
      - Short recap of Rust wasm-bindgen
      - How would this look in other languages?  Is there an opportunity to share/regularize backend tools?
- [x] [JavaScript BigInt to WebAssembly i64 integration](https://github.com/WebAssembly/design/issues/1186) (champion @littledan - [phase 2](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#2-proposed-spec-text-available-community--working-group))
- [x] [Web Content Security Policy](https://github.com/WebAssembly/design/issues/1122) (champion **none** - [phase 0](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#0-pre-proposal-community-group))
    * [How does CSP affect postMessaging of Modules](https://github.com/WebAssembly/content-security-policy/pull/16)
- [ ] [Non-trapping float-to-int conversions](https://github.com/WebAssembly/design/issues/1143) (champion @sunfishcode - [phase 4](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#4-standardize-the-feature-working-group))
- [ ] [Sign-extension operators](https://github.com/WebAssembly/design/issues/1178) (champion @binji - [phase 4](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#4-standardize-the-feature-working-group))
- [ ] [Type Reflection for WebAssembly JavaScript API](https://github.com/WebAssembly/design/issues/1181) (champion @tschneidereit  - [phase 1](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#1-feature-proposal-community-group))
- [ ] [Unmanaged closures](https://github.com/WebAssembly/design/issues/1182) (champion @erights - [phase 0](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#0-pre-proposal-community-group))
- [ ] [Custom Annotation Syntax in the Text Format](https://github.com/WebAssembly/design/issues/1192) (champion @rossberg - [phase 1](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#1-feature-proposal-community-group))
- [ ] [Fixed-width SIMD](https://github.com/WebAssembly/design/issues/1075) (champion **none** - [phase 1](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#1-feature-proposal-community-group))
- [ ] [Exception handling](https://github.com/WebAssembly/design/issues/1078) (champion @aheejin  - [phase 1](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#1-feature-proposal-community-group))

I'm guessing that we won't need any discussion on the [phase 4](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#4-standardize-the-feature-working-group) proposals.

If you are a champion of one of these proposals, please respond whether you are planning to go to this CG meeting to discuss your proposal.

I believe we will need some new champions for some of these proposals, so if you are a current champion and would no longer like to be, please respond here too.

**Comment by stoklund** [comment]
I have to step down as SIMD champion. New job.

**Comment by binji** [comment]
Thanks, @stoklund, I've removed you from the tracking issue.

**Comment by linclark** [comment]
I am planning to go to this CG meeting to discuss ES module integration.

**Comment by rossberg** [comment]
The topics I would like to discuss are

* Tail calls
* Garbage collection
* Memory model and spec for threads (with Conrad)

There are also the phase 3 proposals: multi values and reference types. These are currently blocked on implementation work in engines. If engines make sufficient progress by October then I'd like to discuss moving them forward to stage 4. Otherwise there probably isn’t much to discuss, though I could just give a 2 minute update.

As mentioned in a recent VC, I’m looking for somebody to help with or take over championing the JS type reflection proposal.

**Comment by littledan** [comment]
I'm coming to the CG meeting.

**Comment by binji** [comment]
Thanks, @rossberg, I've added an agenda item to the next CG meeting to discuss finding new champions for a handful of these proposals.

**Comment by conrad-watt** [comment]
Sorry, I didn't realise that clicking and dragging on the list causes the issue to be edited inline. I've deleted my accidental change.

I may as well take this opportunity to say that I'm coming to TPAC and can talk about the threads memory model.

**Comment by binji** [comment]
Thanks, Conrad. I'll start putting together a schedule this week in [TPAC.md](https://github.com/WebAssembly/meetings/blob/master/2018/TPAC.md).

**Comment by titzer** [comment]
It would be good to be able to have the exception discussion when people from MTV can dial in. Maybe it fits better on Thursday afternoon?

**Comment by chicoxyzzy** [comment]
Will it be possible to join online as observer?

**Comment by binji** [comment]
@chicoxyzzy We were able to set up the room to use the same zoom.us meeting ID as the WebAssembly CG meeting.

For anyone else who may be reading this, if you are a member of the CG, you can send me an email at binji@google.com and I will send you the meeting ID.

**Comment by binji** [comment]
Meeting over, thanks to all who presented and attended!
